name: LONDON-CRAWL
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39279
title: LONDON PUB CRAWL - 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#fffffa'
    - '#8b8168'
    - '#61573e'
    - '#cf6500'
  brandStrength: 0.018734853016212583
  lightness: 0.7200860504526645
  saturation: 0.0027314021717756987
  rhythmicContrast: 0.44387124944478273
purpose: []
