name: LONDON-CRAWL
favicon: null
layout_spectrum: 0.19778
typography_spectrum: 0.39279
title: LONDON PUB CRAWL - 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#fffffa'
    - '#8b8168'
    - '#61573e'
    - '#cf6500'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.44387124944478273
purpose: []
